title: !Germany wiki
description: A wiki for the !Germany community on the threadiverse
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  to the threadiverse: https://feddit.de/c/germany
